plugins:
  - aws-amplify-serverless-plugin
  - serverless-appsync-plugin
  - serverless-pseudo-parameters

custom:
  amplify:
    - filename: examples/awsconfiguration.json
      type: native
      appClient: AndroidUserPoolClient
      s3bucket: UserFiles
    - filename: examples/schema.json
      type: schema.json
    - filename: examples/aws-exports.js
      type: javascript
      appClient: WebUserPoolClient
      s3bucket: disabled
